<a href="https://colab.research.google.com/github/hkokin/ekpa/blob/main/askisi1_git.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [ ]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0       slashdot.org        0        0           1          3            0   
1    sriutamahub.com        0        0           1          2            0   
2  vipdomainshop.com        0        0           1          3            0   
3      aljazeera.net        0        0           1          6            0   
4     upd-medlav.net        0        0           1          2            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           1            1           1   
1             0        0              0           0            1           0   
2             0        0              0           1            1           1   
3             0        0              0           0            1           1   
4             0        0              1           0            1           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           1       0           0            1             0      1  
2           1       0           0            1             0      1  
3           1       0           0            1             0      0  
4           1       0           0            1             0      1

In [ ]:
X = data.drop(['Domain', 'Label'], axis=1)

In [ ]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          3            0             0   
1        0        0           1          2            0             0   
2        0        0           1          3            0             0   
3        0        0           1          6            0             0   
4        0        0           1          2            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           1            1           1           1   
1        0              0           0            1           0           1   
2        0              0           1            1           1           1   
3        0              0           0            1           1           1   
4        0              1           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [ ]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [ ]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8
Precision: 0.8249568418282035
Recall: 0.8
F1 Score: 0.7958428529194986
Confusion Matrix:
[[1419   91]
 [ 509  981]]

SVC Metrics:
Accuracy: 0.8246666666666667
Precision: 0.854685459461851
Recall: 0.8246666666666667
F1 Score: 0.8206653442903392
Confusion Matrix:
[[1466   44]
 [ 482 1008]]

RandomForestClassifier Metrics:
Accuracy: 0.8526666666666667
Precision: 0.8564249867863188
Recall: 0.8526666666666667
F1 Score: 0.8522156494768363
Confusion Matrix:
[[1367  143]
 [ 299 1191]]

MLPClassifier Metrics:
Accuracy: 0.848
Precision: 0.8596716296333156
Recall: 0.848
F1 Score: 0.846645787379458
Confusion Matrix:
[[1418   92]
 [ 364 1126]]

KNeighborsClassifier Metrics:
Accuracy: 0.8343333333333334
Precision: 0.8392563088511391
Recall: 0.8343333333333334
F1 Score: 0.8336463711081848
Confusion Matrix:
[[1353  157]
 [ 340 1150]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8533333333333334
Precision: 0.8580452654099493
Recall: 0.8533333333333334
F1 Score

In [ ]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
5  DecisionTreeClassifier  0.853333   0.858045  0.853333  0.852781
2  RandomForestClassifier  0.852667   0.856425  0.852667  0.852216
3           MLPClassifier  0.848000   0.859672  0.848000  0.846646
4    KNeighborsClassifier  0.834333   0.839256  0.834333  0.833646
1                     SVC  0.824667   0.854685  0.824667  0.820665
0      LogisticRegression  0.800000   0.824957  0.800000  0.795843
